# load("@com_google_protobuf//:protobuf.bzl", "py_proto_library")
load("//protos:protobuf.bzl", "py_proto_library")

package(default_visibility = ["//visibility:public"])

py_proto_library(
    name = "yfinance_py",
    srcs = ["yfinance.proto"]
)
